version: "3"
services:
  api:
    # Quando jรก tiver uma imagem da api
    image: alexvecchi/api-ts_api:mytag
    # Gera a imagem e sobe a mesma 
    #build: .
    ports:
      - "3050:3050"
    links:
      - link-db
  link-db:
    image: tutum/mongodb
    ports:
      - "27017:27017"
      - "28017:28017"
    environment:
      - AUTH=no
