version: "3"
services:
  api:
    # Quando jรก tiver uma imagem da api
    image: alexvecchi/api-ts
    # Gera a imagem e sobe a mesma 
    # build: .
    # image: alexvecchi/api-ts
    ports:
      - "80:3050"
    links:
      - link-db
  link-db:
    image: tutum/mongodb
    ports:
      - "27017:27017"
      - "28017:28017"
    environment:
      - AUTH=no
